### ISSUE TITLE
Excessive whitespace in output.

### ISSUE THREAD

**Issue by cconger** [ef4/broccoli-sourcemap-concat#13]
I've created a gist which has the basic production output of a ember-cli 0.2.7 application into two files: simpleapp.js and vendor.js.  If I attempt to concat them and preserve their sourcemaps using this broccoli extension I'm given an output file containing approximately 70,000 lines of whitespace, which seems like undesired behavior.  It seems that this only occurs when minification (sourcemap preserving uglify2) is applied to the files beforehand.

Here is the gist:
https://gist.github.com/cconger/c8f3e5150585545cf70b

I also included a sample Brocfile.

Relevant versions:
ember-cli 0.2.7
broccoli: 0.16.7
broccoli-sourcemap-concat: 1.0.2
node: v0.12.7
OS: Mac OS 10.10.4 and on CentOS

**Comment by stefanpenner** [comment]
> ember-cli 0.2.7

this seems like a very old version of ember-cli. I would recommend upgrading and seeing if latest (which also include 2x broccoli-sourcemap-concat) fixes your issue.
