### ISSUE TITLE
EISDIR: illegal operation on a directory, read

### ISSUE THREAD

**Issue by ef4** [ef4/broccoli-sourcemap-concat#19]
@stefanpenner: #18 seems to have introduced a bug.

The code that was removed was doing an explicit `isDirectory` check. That check was needed because sometimes directories match patterns like "*.js".

If you have an input tree that contains `bower_components/loader.js/loader.js` and try to concat "*.js", we hit an EISDIR.

**Comment by stefanpenner** [comment]
Ah, we will need to add a regression test, so future work does not cause us grief.

I can take a look this afternoon, maybe 3 hours or so. Feel free to issue a hot-fix in the interim.
