### ISSUE TITLE
Potential regression

### ISSUE THREAD

**Issue by stefanpenner** [ef4/broccoli-sourcemap-concat#21]
I believe I may have regressed something, am investigating.

moment.js is getting concated twice in our app.

**Comment by ef4** [comment]
Last time I saw that scenario, it was because a file in headerFiles also matched the general inputFiles pattern.

We don't actually de-dup correctly in that scenario, and we probably should.

**Comment by stefanpenner** [comment]
@ef4 ah interesting.

Just about to sit down and dig into this.
