### ISSUE TITLE
Latest version failure with `ember.js`: `enifed is not a function`

### ISSUE THREAD

**Issue by duggiefresh** [ef4/broccoli-sourcemap-concat#24]
Emberjs issue: https://github.com/emberjs/ember.js/issues/12366

Unfortunately, I am not entirely familiar with this lib. So I'll just describe the bug. :)

---

Pulling the latest `Ember.js`, and nombom'ing causes the build to break. Seems that @rwjblue and @mixonic debugged the problem and found that version `1.0.2` works with the latest Ember version.

Here's my humble screenshot.

---

![screen shot 2015-09-18 at 11 27 18 am](https://cloud.githubusercontent.com/assets/1206678/9963942/ad7d78d0-5dfb-11e5-8efc-54f54e57b8cf.png)

**Comment by rwjblue** [comment]
I believe this is related to the prior issue WRT `isDirectory` checks.  In Ember's build, we do [this](https://github.com/emberjs/emberjs-build/blob/49b908055c65c555885fa6450ce28c1b4b555def/lib/concatenate-es6-modules.js#L47) to prepend `loader.js`, but it seems that this is no longer working.  The interesting thing is that the string `loader.js` passed to `inputFiles` is completely ignored (it may be that this is treated as a glob?), but either way the resulting `ember.debug.js` does not include the loader or IIFE start/stop segments from emberjs-build file linked above.

^^ is mostly just a quick brain dump, I will try to dig further tonight...

**Comment by stefanpenner** [comment]
i'll take a look
