### ISSUE TITLE
Ordering option?

### ISSUE THREAD

**Issue by marcioj** [ef4/broccoli-sourcemap-concat#27]
When using globals it's very common to need a predetermined order of the files. For instance if we have a bunch of jquery plugins `jquery.js` have to be loaded before `jquery.someplugin.js`. But right now there is no way to have such control. Would you guys accept this option?

**Comment by ef4** [comment]
`headerFiles` and `footerFiles` are both ordered. `inputFiles` goes in between them, and is for things where you don't care about the order.

**Comment by stefanpenner** [comment]
Will reopen if the above explanation does not cover the problem.

**Comment by marcioj** [comment]
Thanks for the explanation, it worked perfectly!

**Comment by stefanpenner** [comment]
:+1: 

I tried to update the docs to convey this, but if you have an idea on how to improve. Let me know (or submit a PR)
