### ISSUE TITLE
[Performance] Consider multiple inputNodes

### ISSUE THREAD

**Issue by stefanpenner** [ef4/broccoli-sourcemap-concat#28]
The following pattern is quite common:

``` js
outputFile = concat(merge(manyTrees));
```

some real examples:
- https://github.com/emberjs/emberjs-build/blob/master/lib/concatenate-es6-modules.js#L77
- https://github.com/emberjs/emberjs-build/blob/fa7b8c0b063384f2155159b96dc363f9dd27cf95/lib/build-cjs-tree.js#L13
- https://github.com/emberjs/emberjs-build/blob/fa7b8c0b063384f2155159b96dc363f9dd27cf95/lib/get-build-runtime-tree.js#L51
- https://github.com/emberjs/emberjs-build/blob/fa7b8c0b063384f2155159b96dc363f9dd27cf95/lib/get-build-template-compiler-tree.js#L47

ember.js build slow trees:

``` js
Build successful - 825ms.

Slowest Trees                                 | Total
----------------------------------------------+---------------------
ConcatWithMaps                                | 130ms
BroccoliMergeTrees                            | 85ms
BroccoliMergeTrees                            | 74ms
BroccoliMergeTrees                            | 58ms
BroccoliMergeTrees                            | 44ms

Slowest Trees (cumulative)                    | Total (avg)
----------------------------------------------+---------------------
BroccoliMergeTrees (34)                       | 433ms (12 ms)
ConcatWithMaps (8)                            | 175ms (21 ms)
Babel (19)                                    | 77ms (4 ms)
```

Now obviously mergeTrees can be made much faster
1. short term: https://github.com/hjdivad/broccoli-merge-trees/tree/merge-using-fs-tree-diff (persistentOutput + patch based management)
2. long term, mergeTree merely mutating some internal state object in broccoli.

But even given the work that can be done to improve mergeTrees, it appears that maybe the missing piece is `concat` not handling multiple inputNodes.

---

I would like to propose concat learning a simple right to left merge, given higher precedents to files in the right most inputNodes.

``` js
var outputFile = concat([lowest, middle, highest]);
```

I believe this actually simplifies the model nicely, while providing some nice (shoter term) performance wins.

**Comment by rwjblue** [comment]
> I would like to propose concat learning a simple right to left merge, given higher precedents to files in the right most inputNodes.

:+1:

**Comment by ef4** [comment]
This sounds good to me.

**Comment by stefanpenner** [comment]
I think I once again prefer this being handle by a more aggressive cross plugin broccoli level optimization. Closing for now, I may revisit.
