### ISSUE TITLE
walk-sync update breaks on windows

### ISSUE THREAD

**Issue by chrmod** [ef4/broccoli-sourcemap-concat#34]
please see this issue: https://github.com/joliss/node-walk-sync/issues/21

fixing walk-sync version to 0.2.5 solve the problem

**Comment by stefanpenner** [comment]
https://github.com/joliss/node-walk-sync/issues/21#issuecomment-157402576

**Comment by stefanpenner** [comment]
closed as per: https://github.com/joliss/node-walk-sync/issues/21#issuecomment-164065173
